spring.application.name=van-loading-optimiser
spring.datasource.url=jdbc:postgresql://localhost:5432/vanloading
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.flyway.enabled=true
spring.flyway.locations=classpath:Migrations

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8080